### PR TITLE
Dockerfile maintenance

### PR DESCRIPTION
**Pull request by kotaroooo0**
commit: a2481d5 d8af7a9
I remove unnecessary code!

commit: 52a9aa6
I separate module download to use cache easily.

this docker image is equal to original docker image minus `internal/cmd/generate/vender`

### CODE REVIEW

**Comment by kotaroooo0** [comment]
Could you do code review? @karmi

**Comment by karmi** [comment]
Hello @kotaroooo0 — I'm out of office until the end of the month, I'll have a look when I'm back. The changes look good to me, I would just clean up the commits a bit (single commit, consistent naming, ...).

**Comment by karmi** [comment]
Hi @kotaroooo0, I've updated the patch a bit (updated the example command, gotestsum version, ...), cleaned up the commit message and merged to the main branch. Thanks!

**Comment by karmi** [comment]
Merged into `7.x` and `6.x` branches.

**Pull request closed without merging**
