### PR TITLE
Util: Allow setting version metadata in Bulk Indexer

### LINKED ISSUE #175: Bulk index util should allow specifying version and version type
The Bulk API supports document versioning metadata. These params should be exposed in the BulkIndexerItem struct.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-versioning

### PR DESCRIPTION
**Pull request by munkyboy**
fixes #175

### CODE REVIEW

**Comment by viraths** [comment]
Can we please merge this. I need this as well for handling versions.

**Comment by karmi** [comment]
Hello, there's been a similar PR lately, and this needs to be addressed in a more robust way, allowing to set other supported parameters for the operation (routing, ...). I'm on vacation currently, I'll have a look at it when I'm back.

**Comment by karmi** [comment]
Hello, I'm no longer maintaining the package, so I can't set a date for when this might be picked up. Ultimately, what we need here is some code generation for the bulk item struct, taking an input in JSON/YAML/etc, or other machine readable data, to keep the support in sync with the Elasticsearch Bulk API.

**Comment by munkyboy** [comment]
handled in #265

**Pull request closed without merging**
