### PR TITLE
Reinstate item.Body after it is consumed

### PR DESCRIPTION
**Pull request by l1redd**
This addresses the bug documented here: https://github.com/elastic/go-elasticsearch/issues/161

### CODE REVIEW

**Comment by karmi** [comment]
Hi @l1redd, the patch looks good. I was concerned about using the pointer at first, but it doesn't appear to impact the allocations when I run the benchmarks locally. I see the CLA Checker complains, can you please sign the CLA at https://www.elastic.co/contributor-agreement?

**Comment by l1redd** [comment]
@karmi hey! mind reviewing this bug fix? i have tentative approval from Lyft to sign the CLA but need to get someone from Lyft to look at the PR first

**Comment by l1redd** [comment]
> Hi @l1redd, the patch looks good. I was concerned about using the pointer at first, but it doesn't appear to impact the allocations when I run the benchmarks locally. I see the CLA Checker complains, can you please sign the CLA at https://www.elastic.co/contributor-agreement?

hey! thanks for looking at this! I have tentative approval from Lyft to sign the CLA but need to get someone from there to take a quick look at the PR first.

**Comment by l1redd** [comment]
I'm going to have to close this PR and open up a duplicate one. I was supposed to open this from a public Lyft fork of go-elasticsearch instead of my own. I'll sign the CLA from that one!

**Pull request closed without merging**
