### PR TITLE
Scroll id in the body instead of query

### PR DESCRIPTION
**Pull request by sidenko-dmitrii**
This fix by the issue https://github.com/elastic/go-elasticsearch/issues/166
made by example in the documentation https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-scroll.html. 
The scroll should be the post method and the scroll id should be in the body.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @sidenko-dmitrii , the entire Go API is generated from a JSON specification in the Elasticsearch repository, in this case [`scroll.json`](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/scroll.json). The generator does support overrides, but in this particular case, it doesn't seem like we can and should do anything. The specification does mark the `scroll_id` URL part as deprecated — I'll have a look into marking it accordingly in the Go source code during generation.

Ultimately, the package should provide a helper method to facilitate using the API, similar to `esutil.BulkIndxer`.

**Comment by sidenko-dmitrii** [comment]
@karmi 
The deprecated part is using the scroll_id in path and query:
https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html#scroll-api-path-params
https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html#scroll-api-query-params

**Comment by DmSide** [comment]
@karmi Please take a look on my PR. It is okay. Do you have any comments?

**Comment by karmi** [comment]
As I was saying, the entire Go API is generated, so changing the generated code doesn't really solve the issue (see the comment at the beginning of the file).

Further, the client _intentionally_ stays from any de/serialization, so calling `json.Marshal()` is not applicable.

The only fix we can do in the package is to annotate deprecated arguments, and provide guidelines. A related effort has to happen in the Elasticsearch repository, to properly deprecate and remove the arguments from the URL.

**Comment by Anaethelion** [comment]
Closing this as everything has been said and `api.scroll.go` now uses the `POST` method.

**Comment by cettoana** [comment]
Adding a mention of this issue to the document would be appreciated, cause the Scroll method of the Typed API is completely non-functional, and the user will only get something like

`403, failed: [security_exception], reason: action [indices:data/read/scroll] is unauthorized for user [username] ... `

**Pull request closed without merging**
