### PR TITLE
Refactor to outdent if/else blocks with return statements

### PR DESCRIPTION
**Pull request by HaraldNordgren**
Improves the Go scorecard from here: https://goreportcard.com/report/github.com/elastic/go-elasticsearch#golint

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
Ping @Anaethelion

**Comment by Anaethelion** [comment]
buildkite test this

**Review by Anaethelion — APPROVED** [review]
LGTM, thank you!

**Comment by HaraldNordgren** [comment]
@Anaethelion Thanks for the help!

If you have some more time, these two could also use some attention: https://github.com/elastic/go-elasticsearch/pull/891 and https://github.com/elastic/go-elasticsearch/pull/894.

**Pull request merged**
