### PR TITLE
BulkIndexer - Reinstate item.Body after it is consumed

### PR DESCRIPTION
**Pull request by l1redd**
This addresses the bug documented here: #161
Duplicate of https://github.com/elastic/go-elasticsearch/pull/164

### CODE REVIEW

**Comment by l1redd** [comment]
I signed the CLA! Not sure when that gets reflected here.

**Comment by l1redd** [comment]
The lint failures have to do with two files that I didn't touch. I'm assuming, that I shouldn't address those.

**Comment by karmi** [comment]
You're right — the linter complains about a struct field in the `esapi` package, which is something which has to be addressed in the generator. I'll look into that soon.

Many thanks for the patch! I've tweaked the commit message a bit, to make it more consistent with the repo layout, and merged into the main and `7.x` branches.

**Comment by karmi** [comment]
Merged via 8413c97f and 09b44b16.

**Comment by l1redd** [comment]
thanks so much!

**Pull request closed without merging**
