### PR TITLE
Update connecting.asciidoc to use ‘os’ instead of deprecated ‘ioutil’

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Comment by Anaethelion** [comment]
Hi @HaraldNordgren 

Thank you for this fix!

Could you change the branch target so that we merge this in main ? I'll backport that to `8.12` afterwards.

**Comment by HaraldNordgren** [comment]
@Anaethelion Done!

**Comment by HaraldNordgren** [comment]
@Anaethelion Can you take a look here as well? https://github.com/elastic/go-elasticsearch/pull/793

**Review by Anaethelion — APPROVED** [review]
LGTM!

**Pull request merged**
