### PR TITLE
fix readme

### PR DESCRIPTION
**Pull request by pathcl**
If you try out what's in README.md you'll run into this situation..

amsmac011:condor pathcl$ cat > go.mod <<-END
>   module my-elasticsearch-app
>
>   require github.com/elastic/go-elasticsearch/v8 master
> END

amsmac011:condor pathcl$ cat > main.go <<-END
>   package main
>
>   import (
>     "log"
>
>     "github.com/elastic/go-elasticsearch/v8"
>   )
>
>   func main() {
>     es, _ := elasticsearch.NewDefaultClient()
>     log.Println(elasticsearch.Version)
>     log.Println(es.Info())
>   }
> END

amsmac011:condor pathcl$ go run main.go
main.go:6:5: cannot find package "github.com/elastic/go-elasticsearch/v8" in any of:
	/usr/local/Cellar/go/1.12.6/libexec/src/github.com/elastic/go-elasticsearch/v8 (from $GOROOT)
	/Users/pathcl/go/src/github.com/elastic/go-elasticsearch/v8 (from $GOPATH)

that's why I added GO111MODULE="on"

### CODE REVIEW

**Comment by karmi** [comment]
Hey, what version of Go are you using? Current Go version have some heuristics to switch modules on and off, which should be enough...

**Comment by pathcl** [comment]
@karmi go version go1.12.6 darwin/amd64

**Comment by karmi** [comment]
Not sure what's up in your environment, but when I run this:

```bash
docker run --rm golang:1.12 /bin/sh -c '
mkdir my-elasticsearch-app && cd my-elasticsearch-app

cat > go.mod <<-END
  module my-elasticsearch-app

  require github.com/elastic/go-elasticsearch/v8 master
END

cat > main.go <<-END
  package main

  import (
    "log"

    "github.com/elastic/go-elasticsearch/v8"
  )

  func main() {
    es, _ := elasticsearch.NewDefaultClient()
    log.Println(elasticsearch.Version)
    log.Println(es.Info())
  }
END

go run main.go
'
```

I'm getting:

```
go: finding github.com/elastic/go-elasticsearch/v8 master
go: downloading github.com/elastic/go-elasticsearch/v8 v8.0.0-20190708133838-4ec050682b64
go: extracting github.com/elastic/go-elasticsearch/v8 v8.0.0-20190708133838-4ec050682b64
2019/07/11 13:46:22 8.0.0-SNAPSHOT
2019/07/11 13:46:22 <nil> dial tcp 127.0.0.1:9200: connect: connection refused
```

Go modules should be automatically on when there's a `go.mod` in a directory... Manually switching it on via the environment variable is not something I'd like to add to the README example without a thorough understanding.

**Comment by pathcl** [comment]
Maybe is because I'm running OSX. But no worries I already solve it :)

**Comment by karmi** [comment]
I'm running on Max OS X as well, so that shouldn't be the main issue :)

How did you solve it in the end? Is it OK to close the issue?

**Comment by thecraftman** [comment]
can this work with ubuntu ?

**Comment by karmi** [comment]
@thecraftman, yes, the README example should definitely work on Ubuntu as well.

**Pull request closed without merging**
