### PR TITLE
[README] Add missing res.Body.Close()

### PR DESCRIPTION
**Pull request by denisvmedia**
This is a minor change to the readme file that adds a missing res.Body.Close().

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @denisvmedia, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/go-elasticsearch/pull/127.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by karmi** [comment]
Hi, thanks for the catch! It looks like the commit has `d....v@home` as the email address, and that's why the check fails. Can you fix the mail in your Git configuration, and force push?

**Comment by denisvmedia** [comment]
@karmi I fixed it, thanks :)

**Comment by karmi** [comment]
Thanks for the patch! Merged into `master` and backported into `7.x` and `6.x`.

**Pull request merged**
